# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XHVideoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'XHLoading'

  target 'XHVideoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XHVideoDemoUITests' do
    # Pods for testing
  end

end
